<?php
    $bookIds=$BookVar->bookList($conn);
    if(!empty($_POST['search'])){
        $_SESSION['search']=$_POST['search'];
        $_SESSION['indexPage']=1;
        header("Location:index.php?page=index");
    }
    if(isset($_POST['switchPage'])){
        $_SESSION['indexPage']=$_POST['switchPage'];
        header("Location:index.php?page=index");
    }elseif(isset($_POST['forward'])){
        $_SESSION['indexPage']++;
        header("Location:index.php?page=index");
    }elseif(isset($_POST['backward'])){
        if($_SESSION['indexPage']>1){
            $_SESSION['indexPage']--;
            header("Location:index.php?page=index");
        }
    }
    include 'view/index.php';
?>